BREEDS = [
    ('Abyssinian', '아비시니안'),
    ('American Bobtail', '아메리칸 밥테일'),
    ('American Curl', '아메리칸 컬'),
    ('American Shorthair', '아메리칸 숏헤어'),
    ('American Wirehair', '아메리칸 와이어헤어'),
    ('Balinese', '발리니즈'),
    ('Bengal', '벵갈'),
    ('Birman', '버만'),
    ('Bombay', '봄베이'),
    ('British Longhair', '브리티시 롱헤어'),
    ('British Shorthair', '브리티시 숏헤어'),
    ('Burmese', '버미즈'),
    ('Burmilla', '버밀라'),
    ('Chartreux', '샤르트뢰'),
    ('Chausie', '차우시'),
    ('Cornish Rex', '콘월 렉스'),
    ('Cymric', '킴릭'),
    ('Devon Rex', '데본 렉스'),
    ('Donskoy', '돈스코이'),
    ('Egyptian Mau', '이집션 마우'),
    ('European Burmese', '유러피안 버미즈'),
    ('Exotic Shorthair', '엑조틱 숏헤어'),
    ('Havana Brown', '하바나 브라운'),
    ('Highlander', '하이랜더'),
    ('Himalayan', '히말라얀'),
    ('Japanese Bobtail', '재패니즈 밥테일'),
    ('Javanese', '자바니즈'),
    ('Khao Manee', '카오마니'),
    ('Korat', '코랫'),
    ('Kurilian Bobtail', '쿠릴리안 밥테일'),
    ('LaPerm', '라펌'),
    ('Lykoi', '라이코이'),
    ('Maine Coon', '메인쿤'),
    ('Manx', '맹크스'),
    ('Minskin', '민스킨'),
    ('Munchkin', '먼치킨'),
    ('Nebelung', '네벨룽'),
    ('Norwegian Forest Cat', '노르웨이 숲 고양이'),
    ('Ocicat', '오시캣'),
    ('Oriental Shorthair', '오리엔탈 숏헤어'),
    ('Persian', '페르시안'),
    ('Peterbald', '피터볼드'),
    ('Pixie-bob', '픽시밥'),
    ('Ragamuffin', '라가머핀'),
    ('Ragdoll', '랙돌'),
    ('Russian Blue', '러시안 블루'),
    ('Savannah', '사바나'),
    ('Scottish Fold', '스코티시 폴드'),
    ('Selkirk Rex', '셀커크 렉스'),
    ('Serengeti', '세렝게티'),
    ('Siamese', '샴'),
    ('Siberian', '시베리안'),
    ('Singapura', '싱가푸라'),
    ('Snowshoe', '스노우슈'),
    ('Somali', '소말리'),
    ('Sphynx', '스핑크스'),
    ('Tonkinese', '통키니즈'),
    ('Toyger', '토이거'),
    ('Turkish Angora', '터키시 앙고라'),
    ('Turkish Van', '터키시 반'),
    ('Ukrainian Levkoy', '우크라이니안 레프코이'),
    ('York Chocolate', '요크 초콜릿'),
    ('Korean Shorthair', '코리안 숏헤어'),
    ('domestic shorthair', '도메스틱 숏헤어(믹스)'),
    ('domestic longhair', '도메스틱 롱헤어(믹스)'),
    ('orange tabby', '치즈 태비'),
    ('tuxedo', '턱시도'),
    ('calico', '칼리코(삼색이)'),
    ('tortoiseshell', '트라이컬러(고등어 삼색)'),
    ('silver tabby', '실버 태비'),
    ('mackerel tabby', '고등어 태비'),
]
KO = dict(BREEDS)
